os:
  editPreset: 'nvim'
gui:
  theme:
    selectedLineBgColor:
      - "#11111b" # catppuccin mocha - crust
git:
  paging:
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off
